ALTER SESSION SET "_ORACLE_SCRIPT"=true;


-- Creación de tablas dentro del esquema `SYSTEM`
CREATE TABLE SYSTEM.categorias (
    id NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(145 CHAR) NOT NULL
);

CREATE TABLE SYSTEM.ordenes (
    id NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    fecha DATE NOT NULL,
    total NUMBER(8,2) DEFAULT 0.00 NOT NULL
);

CREATE TABLE SYSTEM.productos (
    id NUMBER(10) GENERATED ALWAYS AS IDENTITY PRIMARY KEY,
    nombre VARCHAR2(145 CHAR) NOT NULL,
    precio NUMBER(8,2) DEFAULT 0.00,
    idCategoria NUMBER(10) NOT NULL,
    CONSTRAINT FK_PRODUCTOS_CATEGORIAS FOREIGN KEY (idCategoria)
        REFERENCES SYSTEM.categorias(id)
        ON DELETE CASCADE
);

CREATE TABLE SYSTEM.detalleOrdenes (
    idOrden NUMBER(10) NOT NULL,
    idProducto NUMBER(10) NOT NULL,
    cantidad NUMBER(10) NOT NULL,
    precio NUMBER(8,2) NOT NULL,
    CONSTRAINT PK_DETALLEORDENES PRIMARY KEY (idOrden, idProducto),
    CONSTRAINT FK_DETALLEORDENES_ORDENES FOREIGN KEY (idOrden)
        REFERENCES SYSTEM.ordenes(id)
        ON DELETE CASCADE,
    CONSTRAINT FK_DETALLEORDENES_PRODUCTOS FOREIGN KEY (idProducto)
        REFERENCES SYSTEM.productos(id)
        ON DELETE CASCADE
);

-- Dar permisos al usuario para administrar sus propias tablas
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.categorias TO SYSTEM;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.ordenes TO SYSTEM;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.productos TO SYSTEM;
GRANT SELECT, INSERT, UPDATE, DELETE ON SYSTEM.detalleOrdenes TO SYSTEM;

