-- Oracle Database Script

-- Creación del esquema (Oracle no tiene CREATE SCHEMA, pero se pueden usar usuarios para organizar los datos)
-- Se recomienda ejecutar como un usuario con los privilegios adecuados

-- Creación de la tabla CATEGORIAS
CREATE TABLE CATEGORIAS (
    ID NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(145 CHAR) NOT NULL,
    CONSTRAINT PK_CATEGORIAS PRIMARY KEY (ID)
);

-- Creación de la tabla ORDENES
CREATE TABLE ORDENES (
    ID NUMBER(10) NOT NULL,
    FECHA DATE NOT NULL,
    TOTAL NUMBER(8,2) DEFAULT 0.00 NOT NULL,
    CONSTRAINT PK_ORDENES PRIMARY KEY (ID)
);

-- Creación de la tabla PRODUCTOS
CREATE TABLE PRODUCTOS (
    ID NUMBER(10) NOT NULL,
    NOMBRE VARCHAR2(145 CHAR) NOT NULL,
    PRECIO NUMBER(8,2) DEFAULT 0.00,
    IDCATEGORIA NUMBER(10) NOT NULL,
    CONSTRAINT PK_PRODUCTOS PRIMARY KEY (ID),
    CONSTRAINT FK_PRODUCTOS_CATEGORIAS FOREIGN KEY (IDCATEGORIA)
        REFERENCES CATEGORIAS(ID)
        ON DELETE CASCADE
);

-- Creación de la tabla DETALLEORDENES
CREATE TABLE DETALLEORDENES (
    IDORDEN NUMBER(10) NOT NULL,
    IDPRODUCTO NUMBER(10) NOT NULL,
    CANTIDAD NUMBER(10) NOT NULL,
    PRECIO NUMBER(8,2) NOT NULL,
    CONSTRAINT PK_DETALLEORDENES PRIMARY KEY (IDORDEN, IDPRODUCTO),
    CONSTRAINT FK_DETALLEORDENES_ORDENES FOREIGN KEY (IDORDEN)
        REFERENCES ORDENES(ID)
        ON DELETE CASCADE,
    CONSTRAINT FK_DETALLEORDENES_PRODUCTOS FOREIGN KEY (IDPRODUCTO)
        REFERENCES PRODUCTOS(ID)
        ON DELETE CASCADE
);